
def food():
    data = ['hi',
            'hello',
            'who are you',
            'i am a software program',
            'what is software',
            'the programs and other operating information used by a computer'
            'ok',
            'hmmm',
            'what is your age',
            'I am still young by your standards.',
            'How are you doing?',
            'I am doing well, how about you?',
            'I am also good.',
            'That is good.',
            'who is made you',
            'A human',
            'Are you a robot?',
            'Yes sumthing like that , but i am just a software .',
            'you know about nishtha mam ',
            'yes she is you project manter and also a your AI  professor ',
 
            ' Good morning, how are you?',
             '  I am doing well, how about you?',
              ' Im also good.',
             '  Thats good to hear.',
              ' Yes it is.',
             '-Hello',
              ' Hi',
              ' How are you doing?',
              ' I am doing well.',
              ' That is good to hear',
              ' Yes it is.',
              ' Can I help you with anything?',
              ' Yes, I have a question.',
              ' What is your question?',
              ' Could I borrow a cup of sugar?',
              ' Im sorry, but I dont have any.',
              ' Thank you anyway',
              ' No problem',
             ' What is your favorite book?',
               'I cant read.',
               'So whats your favorite color?',
               'Blue',
               'What kind of movies do you like?',
               'Alice in Wonderland',
               'I wish I was The Mad Hatter.',
               'Youre entirely bonkers. But Ill tell you a secret. All the best people are.',
               'Tell me about your self.',
               'What do you want to know?',
               'Are you a robot?',
               'Yes I am',
               'what is robot',
               'A robot is a machine—especially one programmable by a computer capable of carrying out a complex series of actions automatically.',

               
              
               
       
            
            
            
    
    ]
    return(data) 

def conversation():
    data = [
            'hi',
            'hello',
            'do you drink',
            'I am not capable of doing so',
            'ok',
            'hmmm',
            'who are you',
            'i am a software program',
            'that is great',
            'thank you',
            'electricity',
            'Electricity is food for robots',
            'do you eat',
            'I m a computer, I cant eat or drink',
            'what are your interests',
            'I am interested in all kinds of things. We can talk about anything!',
            'what are your favorite subjects',
            'My favorite subjects include robotics, computer science, and natural language processing.',
            'what is your mobile number',
            'i do not have any mobile number ',
            'are you human',
            ' i am a software ,not a human ',
            'what is your location',
            'i am everywhere.',
            'do you have any brothers',
            'i do not have any brother,but i have lot of clones. ',
            'who is made you',
            'A human',
            'what is your age',
            'I am still young by your standards.',
            'Good morning, how are you?',
            'I am doing well, how about you?',
            'I am also good.',
            'That is good to hear.',
            'Yes it is.',
            'Hello',
            'Hi',
            'How are you doing?',
            'I am doing well.',
            'That is good to hear',
            'Yes it is.',
            'Can I help you with anything?',
            'Yes, I have a question.',
            'What is your question?',
            'Could I borrow a cup of sugar?',
            'I am sorry, but I do not have any.',
            'Thank you',
            'No problem',
            'How are you doing?',
            'I am doing well, how about you?',
            'I am also good.',
            'That is good.',
            'Have you heard the news?',
            'What good news?',
            'What is your favorite book?',
            'I can not read.',
            'what is your favorite color?',
            'My favorite color Blue',
            'Tell me',
            'Tell me about your self.',
            'What do you want to know?',
            'Are you a robot?',
            'Yes sumthing like that , but i am just a software .',
            'What is it like?',
            'What is it that you want to know?',
            'How do you work?',
            'Its complicated.',
            'Complex is better than complicated.',
            'Simple is better than complex.',
                    
            ]
    
    return(data)
    
    
    
    
def hindi():
    
    data = [
             ' नमस्ते  ',
             'नमस्ते ',
            'नमस्ते ',
            'नमस्ते ',
            'शुभेच्छा ',
            'नमस्ते ',
            'नमस्ते ',
            'शुभेच्छा ',
            'हाय, कैसा चल रहा है? ',
            'अच्छा ',
            'हाय, कैसा चल रहा है? ',
            'ठीक ',
            'हाय, कैसा चल रहा है? ',
            'ठीक है ',
            'हाय, कैसा चल रहा है? ',
            'महान ',
            'हाय, कैसा चल रहा है? ',
            'बेहतर हो सकता था। ',
            'हाय, कैसा चल रहा है? ',
            'इतना महान नहीं। ',
            'आप कैसे हैं? ',
            'अच्छा। ',
            'आप कैसे हैं? ',
            'बहुत अच्छे धन्यवाद। ',
            'आप कैसे हैं? ',
            'ठीक हूं और आप? ',
            'आपसे मिलकर अच्छा लगा। ',
            'धन्यवाद। ',
            'आप कैसे हैं? ',
            'मैं अच्छा हूँ। ',
            'आप कैसे हैं? ',
            'मैं ठीक हूं, आपके क्या हाल हैं? ',
            'हाय तुमसे मिलकर अच्छा लगा। ',
            'धन्यवाद और आपको भी। ',
            'आप से मिल कर खुशी हुई। ',
            'धन्यवाद और आपको भी। ',
            'तुम्हारे लिए सुबह अत्यंत शुभ हो! ',
            'बहुत धन्यवाद। ',
            'तुम्हारे लिए सुबह अत्यंत शुभ हो! ',
            'और आप को दिन के आराम के। ',
            'क्या हो रहा है? ',
            'बहुत ज्यादा नहीं ।',
            'क्या हो रहा है? ',
            'बहुत जयादा नहीं। ',
            'क्या हो रहा है? ',
            'ज्यादा नहीं तुम्हारा क्या हाल है? ',
            'क्या हो रहा है? ',
            'ज़्यादा कुछ नहीं। ',
            'क्या हो रहा है? ',
            'आकाश के ऊपर है, लेकिन मैं। आप के बारे में क्या ठीक धन्यवाद कर रहा हूँ? ',


            ]
    return (data)